# Generated by Django 4.1.1 on 2022-10-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unidades', models.IntegerField(verbose_name='cantidad de unidades')),
                ('nombre', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
            },
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='cantidad_unidades',
        ),
        migrations.AddField(
            model_name='modulo',
            name='materiales',
            field=models.ManyToManyField(to='api.material', verbose_name='materiales'),
        ),
    ]
