# Generated by Django 4.1.1 on 2022-11-25 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_remove_libro_usuario_libro_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='modulo',
            name='usuarios',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='usuarios'),
        ),
    ]
