# Generated by Django 4.1.1 on 2022-11-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_modulo_usuario_modulo_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='libro',
            name='asignatura',
            field=models.CharField(max_length=80, unique=True, verbose_name='subject'),
        ),
    ]
