# Generated by Django 4.1.1 on 2022-11-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_libro_fecha_alter_libro_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='cantidad_unidades',
        ),
    ]
