# Generated by Django 4.1.1 on 2022-11-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_libro_cantidad_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad_unidades',
            field=models.IntegerField(default=0, verbose_name='cantidad de unidades'),
            preserve_default=False,
        ),
    ]
