# Generated by Django 4.1.1 on 2022-12-06 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_libro_cantidad_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='usuarios'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='usuarios'),
        ),
    ]
