# Generated by Django 4.1.1 on 2022-12-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_libro_usuarios_alter_modulo_usuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'material', 'verbose_name_plural': 'materiales'},
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='anno_escolar',
        ),
        migrations.AddField(
            model_name='modulo',
            name='categoria',
            field=models.CharField(default='4to', max_length=70, verbose_name='category'),
            preserve_default=False,
        ),
    ]
