# Generated by Django 4.1.1 on 2022-12-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_material_options_remove_modulo_anno_escolar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='categoria',
            field=models.CharField(max_length=70, unique=True, verbose_name='category'),
        ),
    ]
