# Generated by Django 4.1.1 on 2023-01-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_modulo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='materiales',
            field=models.ManyToManyField(blank=True, to='api.material', verbose_name='materiales'),
        ),
    ]
