# Generated by Django 4.1.1 on 2022-10-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('administador', 'administador'), ('secretario', 'secretario'), ('planificador', 'planificador')], default='', max_length=25, verbose_name='rol'),
            preserve_default=False,
        ),
    ]
