# Generated by Django 4.1.1 on 2022-11-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('administrador', 'administrador'), ('secretario', 'secretario'), ('planificador', 'planificador'), ('estudiante', 'estudiante')], max_length=25, verbose_name='rol'),
        ),
    ]
